### ISSUE TITLE
Seeking help for 1189:8890

### ISSUE THREAD

**Issue by Kinnyeo** [kamaaina/macropad_tool#13]
Hello,
first of all thanks for bringing up this tool. It seems to be helpful. Although I am trying to program my 4x1 keyboard with no knobs and my example .ron file look like this:
![image](https://github.com/kamaaina/macropad_tool/assets/77890354/13159a6d-eeef-47bf-bc88-1b2c70c5b689)

After running the validation command with -d argument it tells me everything is super fine:
![image](https://github.com/kamaaina/macropad_tool/assets/77890354/bb8d94a0-f45c-463b-ae3b-913899775204)

Finally I type the push command which returns me this:
![image](https://github.com/kamaaina/macropad_tool/assets/77890354/70a9b81e-fb96-4c08-b8cd-774e87b06cdf)

I am very happy and all that it tells me (in japanese) "Device programming is complete"...

...but nothing seems to be working when I'm pressing the keys. It doesn't give any output. I tried with an online keyboard tester and nothing's there aswell :c
I mean the reason obviously could be that I'm running this on WSL lmao, but after all even the device responds to me that the programming is complete right? Can You help me with this issue please?

**Comment by kamaaina** [comment]
こんにちは、連絡してありがとうございます。マッピングファイルがちょっと違うと思います。
thanks for contacting me about your issue. i think your mapping file might be a bit different. i have only seen the 4 key macropads with one layer. therefore, i think your mapping file should be this:
![mapping](https://github.com/kamaaina/macropad_tool/assets/4704715/0d739470-efa2-4afc-b7a2-f2bfac52e0ed)

i have just tried it on my device and it was programmed successfully (on linux and windows). i have not tried it using WSL before, but have you tried to do it through windows? yes,  since you did not get any errors, it should have been programmed, but please try it on windows if you are able to.

i have recently updated the code, so could you please try the latest version (ie. git pull)?
お願いします

**Comment by Kinnyeo** [comment]
Hello again, I'd like to report that the programming **worked** this time :)
The issue is WSL and binding device through usbipd. For some reason once it's detached via usbipd it seems to freak out. But for future notice, using WSL is not a good idea - I just used Visual Studio this time.

**Comment by kamaaina** [comment]
glad it worked! thanks for the information with WSL
